export type Exercise = {
  slug: string;
  short: string;
  name: string;
  muscle: "Chest" | "Back" | "Legs" | "Shoulders" | "Arms" | "Abs" | "Cardio";
  equipment: string;
  level: string;
  recommended: string;
  description: string;
  steps: string[];
  cues: string[];
};

export const exercises: Exercise[] = [
  {slug:"barbell-bench-press",short:"BP",name:"Barbell Bench Press",muscle:"Chest",equipment:"Barbell",level:"Intermediate",recommended:"3–5 sets · 5–10 reps",description:"A foundational horizontal pressing exercise for chest, triceps and anterior shoulder strength.",steps:["Set your upper back firmly on the bench.","Lower the bar with control toward the lower chest.","Press the bar upward while keeping your torso stable."],cues:["Keep feet planted.","Maintain controlled bar path.","Do not bounce the bar off the chest."]},
  {slug:"incline-dumbbell-press",short:"IDP",name:"Incline Dumbbell Press",muscle:"Chest",equipment:"Dumbbells",level:"Beginner",recommended:"3–4 sets · 8–12 reps",description:"An upper-chest focused press that also develops shoulder stability.",steps:["Set bench to a moderate incline.","Start dumbbells beside the upper chest.","Press up and slightly inward."],cues:["Avoid excessive bench angle.","Keep shoulder blades controlled.","Use full comfortable range."]},
  {slug:"lat-pulldown",short:"LP",name:"Lat Pulldown",muscle:"Back",equipment:"Cable",level:"Beginner",recommended:"3–4 sets · 8–12 reps",description:"A vertical pulling exercise for lats, upper back and elbow flexors.",steps:["Set thighs securely under the pad.","Pull the bar toward the upper chest.","Return slowly until arms are extended."],cues:["Drive elbows down.","Avoid excessive leaning.","Control the stretch."]},
  {slug:"seated-cable-row",short:"CR",name:"Seated Cable Row",muscle:"Back",equipment:"Cable",level:"Beginner",recommended:"3–4 sets · 8–15 reps",description:"A horizontal row for mid-back strength and scapular control.",steps:["Sit tall with neutral spine.","Pull handle toward torso.","Return under control."],cues:["Do not jerk backward.","Lead with elbows.","Finish with controlled shoulder blades."]},
  {slug:"back-squat",short:"SQ",name:"Back Squat",muscle:"Legs",equipment:"Barbell",level:"Intermediate",recommended:"3–5 sets · 5–10 reps",description:"A compound lower-body exercise for quads, glutes, trunk and overall strength.",steps:["Position the bar securely.","Brace before descending.","Stand by driving through the floor."],cues:["Keep full-foot pressure.","Control depth.","Maintain a braced torso."]},
  {slug:"romanian-deadlift",short:"RDL",name:"Romanian Deadlift",muscle:"Legs",equipment:"Barbell",level:"Intermediate",recommended:"3–4 sets · 6–12 reps",description:"A hip-hinge movement emphasizing hamstrings, glutes and posterior-chain control.",steps:["Start tall with the bar close to thighs.","Push hips backward while maintaining control.","Stand by extending the hips."],cues:["Keep bar close.","Do not turn it into a squat.","Stop before spinal position is lost."]},
  {slug:"shoulder-press",short:"SP",name:"Shoulder Press",muscle:"Shoulders",equipment:"Dumbbells",level:"Beginner",recommended:"3–4 sets · 8–12 reps",description:"A vertical press for deltoids and triceps.",steps:["Set dumbbells near shoulder height.","Press overhead smoothly.","Lower with control."],cues:["Keep ribs controlled.","Avoid excessive arching.","Use a stable base."]},
  {slug:"lateral-raise",short:"LR",name:"Lateral Raise",muscle:"Shoulders",equipment:"Dumbbells",level:"Beginner",recommended:"3–4 sets · 12–20 reps",description:"An isolation movement focused on the lateral deltoid.",steps:["Stand tall with light dumbbells.","Raise arms outward under control.","Lower slowly."],cues:["Use manageable weight.","Do not swing.","Keep tension consistent."]},
  {slug:"dumbbell-curl",short:"DC",name:"Dumbbell Curl",muscle:"Arms",equipment:"Dumbbells",level:"Beginner",recommended:"3–4 sets · 8–15 reps",description:"A simple elbow-flexion exercise for biceps development.",steps:["Start with arms by sides.","Curl without moving upper arms forward.","Lower fully under control."],cues:["Avoid swinging.","Control the eccentric.","Keep wrists neutral."]},
  {slug:"rope-pushdown",short:"RP",name:"Rope Pushdown",muscle:"Arms",equipment:"Cable",level:"Beginner",recommended:"3–4 sets · 10–15 reps",description:"A cable triceps exercise with consistent resistance.",steps:["Set elbows beside torso.","Extend arms downward.","Return until triceps are stretched."],cues:["Keep elbows stable.","Do not lean excessively.","Finish each rep fully."]},
  {slug:"cable-crunch",short:"CC",name:"Cable Crunch",muscle:"Abs",equipment:"Cable",level:"Beginner",recommended:"3–4 sets · 10–20 reps",description:"A loaded trunk-flexion exercise for abdominal strength.",steps:["Kneel facing the cable.","Brace and flex through the trunk.","Return under control."],cues:["Move through the torso.","Avoid pulling with arms.","Use controlled resistance."]},
  {slug:"plank",short:"PL",name:"Plank",muscle:"Abs",equipment:"Bodyweight",level:"Beginner",recommended:"3 sets · 30–60 sec",description:"An isometric core exercise for trunk stability.",steps:["Set elbows under shoulders.","Create a straight body line.","Hold while breathing under tension."],cues:["Do not sag hips.","Keep glutes active.","Maintain steady breathing."]},
  {slug:"treadmill-run",short:"TR",name:"Treadmill Run",muscle:"Cardio",equipment:"Treadmill",level:"All levels",recommended:"15–40 minutes",description:"Adjustable indoor running or walking for aerobic conditioning.",steps:["Start at manageable pace.","Build speed gradually.","Cool down before stopping."],cues:["Use natural stride.","Avoid holding rails unless needed.","Match intensity to training goal."]},
  {slug:"rowing-machine",short:"RM",name:"Rowing Machine",muscle:"Cardio",equipment:"Rower",level:"All levels",recommended:"10–30 minutes",description:"Full-body cardiovascular conditioning using repeated drive and recovery phases.",steps:["Drive with legs first.","Finish with torso and arms.","Reverse smoothly during recovery."],cues:["Keep sequence consistent.","Avoid rushing recovery.","Use sustainable pacing."]},
];
