"use client";
import type {ReactNode} from "react";import Link from "next/link";import {usePathname} from "next/navigation";
const groups: Array<[string, Array<[string, string]>]> = [
["Coach",[["Overview","/trainer"],["Clients","/trainer/clients"],["Schedule","/trainer/schedule"],["Sessions","/trainer/sessions"]]],
["Programming",[["Assign Workout","/trainer/assign-workout"],["Assign Diet","/trainer/assign-diet"],["Progress","/trainer/progress"],["Notes","/trainer/notes"]]],
["Business",[["Earnings","/trainer/earnings"]]]
];
export function TrainerShell({title,subtitle:copy,children}:{title:string;subtitle?:string;children:ReactNode}){const p=usePathname();const active=(h:string)=>h==="/trainer"?p===h:p===h||p.startsWith(h+"/");return <main style={{minHeight:"100svh",background:"#090909"}}>
<aside className="trainer-sidebar apex-scroll" style={{position:"fixed",inset:"0 auto 0 0",width:260,padding:20,borderRight:"1px solid var(--line)",background:"radial-gradient(circle at 15% 8%,rgba(223,255,0,.065),transparent 22%),#0b0b0b",zIndex:40,overflowY:"auto"}}><Link href="/" style={{display:"flex",gap:10,alignItems:"center",fontWeight:1000,fontSize:18}}><span style={{width:38,height:38,borderRadius:12,display:"grid",placeItems:"center",background:"var(--accent)",color:"#080808"}}>T</span>APEX TRAINER</Link>
<div style={{marginTop:26,display:"grid",gap:20,paddingBottom:26}}>{groups.map(([g,items])=><section key={g}><div className="muted" style={{fontSize:9,fontWeight:1000,letterSpacing:".16em",margin:"0 10px 8px"}}>{g.toUpperCase()}</div><nav style={{display:"grid",gap:6}}>{items.map(([l,h])=>{const a=active(h);return <Link key={h} href={h} style={{minHeight:42,display:"flex",alignItems:"center",padding:"0 12px",borderRadius:12,border:a?"1px solid rgba(223,255,0,.42)":"1px solid transparent",background:a?"rgba(223,255,0,.09)":"transparent",color:a?"var(--accent)":"#f4f4f4",fontSize:12,fontWeight:a?1000:800}}>{l}</Link>})}</nav></section>)}</div></aside>
<div className="trainer-main" style={{marginLeft:260,minWidth:0}}><header style={{minHeight:76,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px clamp(18px,4vw,46px)",borderBottom:"1px solid var(--line)",position:"sticky",top:0,zIndex:20,background:"rgba(9,9,9,.88)",backdropFilter:"blur(16px)"}}><div><strong>Trainer Portal</strong><div className="muted" style={{fontSize:12,marginTop:4}}>Clients, programming and performance.</div></div><div style={{width:42,height:42,borderRadius:13,display:"grid",placeItems:"center",background:"var(--accent)",color:"#080808",fontWeight:1000}}>TR</div></header><section style={{padding:"34px clamp(18px,4vw,46px) 64px",minWidth:0}}><div style={{marginBottom:30}}><div className="eyebrow">Trainer dashboard</div><h1 style={{fontSize:"clamp(40px,5vw,68px)",margin:"12px 0 8px",letterSpacing:"-.055em"}}>{title}</h1>{copy&&<p className="muted" style={{maxWidth:820,margin:0,lineHeight:1.7}}>{copy}</p>}</div>{children}</section></div>
<style>{`@media(max-width:1040px){.trainer-main{margin-left:0!important;padding-bottom:78px}.trainer-sidebar{inset:auto 0 0 0!important;width:auto!important;height:70px;display:flex;align-items:center;overflow-x:auto;overflow-y:hidden;padding:10px 12px!important;border-right:none!important;border-top:1px solid var(--line)}.trainer-sidebar>a{display:none!important}.trainer-sidebar>div{display:flex!important;margin:0!important;padding:0!important;gap:8px!important}.trainer-sidebar section{display:contents!important}.trainer-sidebar section>div{display:none!important}.trainer-sidebar nav{display:flex!important;gap:8px!important}.trainer-sidebar nav a{white-space:nowrap;padding:0 13px!important}}`}</style></main>}
